#!/bin/bash
#
# Generates automatically docker images for Mageia distributions
#
# Based on work done by Fedora and Juan Luis Baptiste
# at https://github.com/juanluisbaptiste/docker-brew-mageia

APPNAME=$(basename $0)

# Workdirs
if [ _"$HOME" = _"" ]; then
	echo "Please define HOME to a sensible value"
	exit -1
fi

# Get env var from the user home dir
if [ -r $HOME/.$APPNAME ]; then
	. $HOME/.$APPNAME
fi

GITDIRRO=${GITDIRRO:=$HOME/tmp/ro-$APPNAME}
GITURLRO=${GITURL:=https://github.com/bcornec}
TMPDM=${WORKDIR:=$HOME/tmp/tmp-$APPNAME}
# By default we host ourselves
MGAMODE=${MGAMODE:="hosted"}
SCPURL=${SCPURL:=localhost:/tmp}
BIGURL=${BIGURL:=http://localhost/$APPNAME}
MGAARCH=${MGAARCH:=x86_64}
# Mirror to consider
#MGAMIRROR=${MGAMIRROR:=http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib}
#ftp://ftp.free.fr/mirrors/mageia.org/distrib/6/armv7hl


# What is our current date
DATE=`date "+%Y-%m-%d"`


usage() {
	echo >&2 "Syntax: $APPNAME [-v Mageia-Version][-m Mageia-Mirror-URL][-w /path/to/workdir]"
	exit 1
}

# Mageia version to consider
# By default the running version if on Mageia
# else generating for cauldron
# Other value could be a number or cauldron
if [ -r /etc/mageia-release ]; then
	MGAVER=`pbdistrocheck | grep Ver: | cut -f2`
	rpm -q docker >& /dev/null
	if [ $? -ne 0 ]; then
		# Install deps in case they're missing
		sudo urpmi docker
	fi
else
	MGAVER=cauldron
fi

# Mirror to consider, by default mirrorlist
MGAMIRROR="https://mirrors.mageia.org/api/mageia.$MGAVER.$MGAARCH.list"

# Get env var from the user home dir
if [ -r $HOME/.$APPNAME ]; then
	. $HOME/.$APPNAME
fi

opt=$(getopt --options 'w:,v:,m:,h,f' --longoptions 'workdir:,version:,mirror:,help,force' --name $APPNAME -- "$@")
eval set -- "$opt"
unset opt
FORCE="false"

while true; do
        case "$1" in
                -v|--version) MGAVER="$2" ; shift 2 ;;
                -m|--mirror) MGAMIRROR="$2" ; shift 2 ;;
                -f|--force) FORCE="true" ; shift ;;
                -w|--workdir) WORKDIR="$2" ; shift ;;
                -h|--help) usage ;;
                 --) shift ; break ;;
        esac
done

TMPDM=${WORKDIR:=$TMPDM}

echo "Creating Mageia $MGAVER ($MGAARCH) container on Docker Hub"

cd $GITDIRRO 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
	echo "$GITDIRRO doesn't exist, creating it"
	mkdir -p $GITDIRRO
	cd $GITDIRRO
	git clone $GITURLRO/$APPNAME .
	if [ $? -ne 0 ]; then
		echo "Unable to clone $GITURLRO"
		exit -1
	fi
fi
git checkout -f master 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
	echo "Unable to checkout branch master"
	exit -1
fi
git branch -D $MGAVER-$MGAARCH 2>/dev/null 1>/dev/null 
git checkout -f --orphan $MGAVER-$MGAARCH
if [ $? -ne 0 ]; then
	echo "Unable to create branch $MGAVER-$MGAARCH"
	exit -1
fi

TARGETDIR="$TMPDM/$MGAVER/$MGAARCH"
echo "Cleanup $TARGETDIR first for idempotence"
sudo rm -rf $TARGETDIR
git rm --cached -r . 2>/dev/null 1>/dev/null

echo "Creating the chroot with latest Mageia $MGAVER content"
sudo /usr/sbin/urpmi.addmedia --distrib --urpmi-root "$TARGETDIR" $MGAMIRROR/$MGAVER/$MGAARCH 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
	echo "Unable to prepare chroot"
	exit -1
fi
sudo LANG=C LANGUAGE=C /usr/sbin/urpmi -q --auto --no-recommends --urpmi-root "$TARGETDIR" basesystem urpmi 2>/dev/null 1>/dev/null
# for armv7hl add --allow-force --force --force-key
if [ $? -ne 0 ]; then
	echo "Unable to prepare install dependencies in chroot"
	exit -1
fi

#
if [ -d "$TARGETDIR/etc/sysconfig" ]; then
	# allow networking init scripts inside the container to work without extra steps
	echo 'NETWORKING=yes' > /tmp/network$$
	sudo install -m 0644 /tmp/network$$ "$TARGETDIR"/etc/sysconfig/network
	rm -f /tmp/network$$
fi

#
# Docker mounts tmpfs at /dev and procfs at /proc so we can remove them
sudo rm -rf "$TARGETDIR/dev" "$TARGETDIR/proc"
sudo install -m 0755 -d "$TARGETDIR/dev" "$TARGETDIR/proc"

# Fix permissions for RPM system
list=`sudo ls "$TARGETDIR"/var/lib/rpm/ | grep -E '^[A-Zi]'`
for f in $list; do
	sudo chmod 644 "$TARGETDIR"/var/lib/rpm/$f
done

# make sure /etc/resolv.conf has something useful in it
cat > /tmp/resolv.conf.$$ << EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
sudo install -m 0644 /tmp/resolv.conf.$$ "$TARGETDIR/etc/resolv.conf"
rm -f /tmp/resolv.conf.$$

# Needs root access for dev files e.g.
echo "Capturing that chroot content into mageia-$MGAVER-$MGAARCH-$DATE.tar.xz"
sudo rm -f mageia-$MGAVER-$MGAARCH-$DATE.tar.xz
sudo tar -C $TARGETDIR -cJf mageia-$MGAVER-$MGAARCH-$DATE.tar.xz .
sudo chmod 644 mageia-$MGAVER-$MGAARCH-$DATE.tar.xz
sudo chroot $TARGETDIR rpm -qa | sort -u > /tmp/rpm-qa-$MGAARCH.$$
# Cleanup
sudo rm -rf $TARGETDIR
if [ -r $HOME/rpm-qa-$MGAVER-$MGAARCH ]; then
	diff -q $HOME/rpm-qa-$MGAVER-$MGAARCH /tmp/rpm-qa-$MGAARCH.$$
	if [ $? -eq 0 ]; then
		echo "The list of RPMs packages didn't change so no need to build a new Docker image"
		if [ $FORCE = "false" ]; then
			exit 1
		fi
	fi
fi

mv -f /tmp/rpm-qa-$MGAARCH.$$ $HOME/rpm-qa-$MGAVER-$MGAARCH
cp $HOME/rpm-qa-$MGAVER-$MGAARCH rpm-qa-$MGAVER-$MGAARCH

echo "Creating the appropriate Docker file"
cat > Dockerfile << EOF
FROM scratch
MAINTAINER bcornec@mageia.org
WORKDIR /
ADD mageia-$MGAVER-$MGAARCH-$DATE.tar.xz /
LABEL name="Mageia $MGAVER Base Image Arch: $MGAARCH" \
    vendor="Mageia" \
    license="GPLv2" \
    build-date="$DATE"
CMD /bin/bash
EOF

echo "Generating the docker image mageiaofficial:$MGAVER-$MGAARCH from it"
docker build -t mageiaofficial:$MGAVER-$MGAARCH . 2>&1 >/dev/null
docker images mageiaofficial:$MGAVER-$MGAARCH
#docker tag mageiaofficial:$MGAVER-$MGAARCH bcornec/mageia:$MGAVER-$MGAARCH
#docker login -u $MGAAC -p $MGAPWD
#docker push bcornec/mageia:$MGAVER-$MGAARCH

if [ _"$MGAMODE" = _"hosted" ] || [ _"$MGAMODE" = _"local" ]; then
	# We host ourselves somewhere on $BIGURL
	perl -pi -e "s|ADD mageia-$MGAVER-$MGAARCH-$DATE.tar.xz|ADD $BIGURL/$MGAVER/$MGAARCH/mageia-$DATE.tar.xz|" Dockerfile
	SSHDIR=`echo $SCPURL | cut -d: -f2`
	if [ _"$MGAMODE" = _"hosted" ]; then
		SSHHOST=`echo $SCPURL | cut -d: -f1`
		echo "Transferring the big file onto $SCPURL"
		ssh $SSHHOST "mkdir -p $SSHDIR/$MGAVER/$MGAARCH ; rm -f $SSHDIR/$MGAVER/$MGAARCH/mageia-$DATE.tar.xz"
		scp -p mageia-$MGAVER-$MGAARCH-$DATE.tar.xz $SCPURL/$MGAVER/$MGAARCH/mageia-$DATE.tar.xz
	else
		if [ _"$KEEP" != _"0" ]; then
			echo "Transferring the big file onto $SCPURL"
			mkdir -p $SSHDIR/$MGAVER/$MGAARCH
			sudo mv mageia-$MGAVER-$MGAARCH-$DATE.tar.xz $SSHDIR/$MGAVER/$MGAARCH/mageia-$DATE.tar.xz
		fi
	fi
else
	# We host on github

	# Automatic build in Docker Hub does not support Git LFS yet
	# Cf: https://github.com/docker/hub-feedback/issues/500
	perl -pi -e "s|ADD mageia-$MGAVER-$MGAARCH-$DATE.tar.xz|ADD $GITURLRO/$APPNAME/$MGAVER/$MGAARCH/mageia-$DATE.tar.xz|" Dockerfile

	# This requires git-lfs for managing large files
	sudo urpmi -q git-lfs 1>/dev/null
	git lfs track "*.tar.xz"
	git add .gitattributes
	git add mageia-$MGAVER-$MGAARCH-$DATE.tar.xz
	# Remove old cached files
	git lfs prune
fi
if [ -f mageia-$MGAVER-$DATE.tar.xz ]; then
	sudo rm -f mageia-$MGAVER-$MGAARCH-$DATE.tar.xz
fi

if [ _"$MGAMODE" = _"local" ]; then
	exit 0
fi

echo "Commiting into our git repo"
git add Dockerfile $APPNAME LICENSE README.md run-mageia rpm-qa-$MGAVER
git commit -m "update Mageia $MGAVER ($MGAARCH) - $DATE"

CID=`git show | head -1 | cut -d' ' -f2`
echo "New commit ID for latest commit is $CID"

if [ _"$MGAMODE" != _"hosted" ]; then
	# Seems we need to do it twice for everything to be pushed with LFS
	git push -f --set-upstream origin $MGAVER
fi

git push -f --set-upstream origin $MGAVER
git checkout -f master
# Backup rpm list for next run
cp $TMPDM/rpm-qa-$MGAARCH rpm-qa-$MGAVER-$MGAARCH
cp $TMPDM/rpm-qa-$MGAARCH $HOME/rpm-qa-$MGAVER-$MGAARCH
git add rpm-qa-$MGAVER-$MGAARCH
git commit -m "update Mageia $MGAVER-$MGAARCH RPM list"
git push

# Doesn't seem to trigger a build with the webhook so forcing it
curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "$MGAVER-$MGAARCH"}' -X POST https://registry.hub.docker.com/u/bcornec/mageia-docker/trigger/$DCKTRIG/

rm -rf $TMPDM

exit 0

git remote update
perl -pi -e 'undef $/; s|(/'$MGAVER'\nGitCommit:) [a-f0-9]+|$1 '$CID'|' mageia
git add mageia
git commit -m "update Mageia commit ID to $CID"
git push origin
