#!/bin/bash
mkdir -p /tmp/docker-mageia
cd /tmp/docker-mageia
if [ "`hostname -s`" = "victoria2" ]; then
	RD="/users"
	WD="$RD/bruno/prj/mageia/"
	MR="ftp://ftp.home.musique-ancienne.org/pub/mageia"
else
	RD="/home"
	WD="$RD/bruno/Maison/bruno/prj/mageia/"
	MR="http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia"
fi
cat > Dockerfile << EOF
FROM mageia:cauldron
MAINTAINER bcornec@mageia.org
#RUN perl -pi -e 's|http://distro.ibiblio.org/mageia|$MR|' /etc/urpmi/urpmi.cfg
#RUN urpmi.update -a -c -f
RUN urpmi.removemedia -a
RUN urpmi.addmedia --probe-hdlist --distrib mga $MR/distrib/cauldron/x86_64
RUN urpmi --auto --auto-select --no-recommends
RUN urpmi --auto bm subversion mgarepo colordiff sudo
RUN sed -i 's/users:x:.*$/users:x:501/' /etc/group
RUN useradd bruno -u 600 -g 501 -N -M -d $RD/bruno
RUN echo "bruno   ALL=(ALL)       NOPASSWD:ALL" >> /etc/sudoers
WORKDIR $WD
USER bruno
CMD ln -sf /users/bruno /home
CMD /bin/bash
EOF

stat=0
docker inspect pb:mageiabuild 2>&1 > /dev/null
if [ $? -eq 0 ]; then
	if [ "$1" = "-f" ]; then
		docker rmi pb:mageiabuild
	fi
else
	docker build --file=Dockerfile -t pb:mageiabuild .
	stat=$?
fi
if [ $stat -eq 0 ]; then
	docker run --rm -v "$SSH_AUTH_SOCK":/ssh-agent -v $RD/bruno:$RD/bruno -e SSH_AUTH_SOCK=/ssh-agent -ti pb:mageiabuild
fi
